apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:toVzGe0Xlgk86aPjf+mjdX3m5V0KUfGYG1xeeSpbG+fRQEjOtcWYhcYiN8MUQVJJ0LABqSy38KGb+luQ2s+ruaQQIZLVWvYikEF3Ze79ZOfprX5hi2F92I/PuIxsmMQyCm01D2+wEX+6zwYTo4qaOHzYx9bzxMCv5IUPYI7KV8CoJMvc8FJokBufQtwQHXwfhKtNBQZ+kqR+2ZkhS3dYWvZMJmXEXatX/DwNJ24fLx2m3aQjACzWFgO0yXDaUl9emjtH2Uhi+zCIzDLGgsiU3A6MtphEFDOM,iv:hBqTp/cfFTVy+yApNSvFdEPWZPlBxuCUnvT/ow1VfYE=,tag:RNduhv3MXDGfW4V40uRmAw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs0qv0zdeyxs493lzh8ay66ksafakkl5c6lg33r9jl037x7kcqsvflujf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQWlvQ2NCUWF4YkRoZ0pM
            NGdaaFlCR0dWV0lPRmdKcFVlZkNxSndwSVE0ClhXZWVHYWdFUDRqZDM4V1JocGZl
            dG16czRlaC9IUnBPNDM4ZzNsTGc5NTAKLS0tIFFqZjBXcCtsQUJWcEluMUhVSlc3
            SXJqVG94bXNXS1NtOEFGTWhKTld5RE0KX8jFvDJtsVPS0CSjcKOzz1/Q9X/+0fo2
            iRdjgithe0SrkLneugRXnFrqkEGi0WY2xaq2rdEWmPUOBOmcWQN8iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T00:26:44Z"
    mac: ENC[AES256_GCM,data:/+Wnne8O/6H7YsMuga/vh0xdL65i166+wiB52t80ymx2aytaJ61Rua4niUGn0+Cv517D50qVjHZH5PZ4S1V4TiktudLICabOGqNaIN4B/TTQUOA3y7SKavyyknk2RQsf/sbYsOSHXKBX1AD/ZfNo1wFiiowEpmxyvAMLfY6CsZY=,iv:EScWsjWzU53pPI/jhJ8ZCI2dVECqe6MJMZuXLKPN8vw=,tag:SGY8X1VmLZ3WvMnwnvt8uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
