apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.4
          volumeMounts:
            - name: audiobookshelf-config
              mountPath: /etc/default/
              readOnly: true
            - name: audiobookshelf-data
              mountPath: /podcasts
            - name: audiobookshelf-data
              mountPath: /audiobooks
            - name: audiobookshelf-data
              mountPath: /metadata
            - name: audiobookshelf-data
              mountPath: /config
          # envFrom:
          #   - configMapRef:
          #       name: audiobookshelf
          ports:
            - containerPort: 80

      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
        - name: audiobookshelf-config
          configMap:
            name: audiobookshelf
            items:
              - key: audiobookshelf
                path: audiobookshelf
