apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.5
          volumeMounts:
            - name: audiobookshelf-configmap
              mountPath: /etc/default/
              readOnly: true
            - name: audiobookshelf-config
              mountPath: /config
            - name: audiobookshelf-podcasts
              mountPath: /podcasts
            - name: audiobookshelf-audiobooks
              mountPath: /audiobooks
            - name: audiobookshelf-metadata
              mountPath: /metadata
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80

      volumes:
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: audiobookshelf-podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
        - name: audiobookshelf-configmap
          configMap:
            name: audiobookshelf
            items:
              - key: audiobookshelf
                path: audiobookshelf
