apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.4
          volumeMounts:
            - name: config
              mountPath: /etc/default/
              readOnly: true
          envFrom:
            - configMapRef:
                name: audiobookshelf
          ports:
            - containerPort: 3005

      volumes:
        - name: config
          configMap:
            name: audiobookshelf
            items:
              - key: audiobookshelf
                path: audiobookshelf
